folders:
  watched: /home/kmbrown/PycharmProjects/ciscofs/watchedDirectory/
  parsed: /home/kmbrown/PycharmProjects/ciscofs/parsedFiles/
  clean: /home/kmbrown/PycharmProjects/ciscofs/cleanFiles/
  error: /home/kmbrown/PycharmProjects/ciscofs/errorFiles/