folders:
  watched: /home/theoretical/cisco/ciscofs/watchedDirectory/
  parsed: /home/theoretical/cisco/ciscofs/parsedFiles/
  clean: /home/theoretical/cisco/ciscofs/cleanFiles/
  error: /home/theoretical/cisco/ciscofs/errorFiles/
