from setuptools import setup

setup(
    name='ciscofs',
    version='',
    packages=['venv.lib.python3.6.site-packages.py', 'venv.lib.python3.6.site-packages.py._io',
              'venv.lib.python3.6.site-packages.py._log', 'venv.lib.python3.6.site-packages.py._code',
              'venv.lib.python3.6.site-packages.py._path', 'venv.lib.python3.6.site-packages.py._process',
              'venv.lib.python3.6.site-packages.py._vendored_packages', 'venv.lib.python3.6.site-packages.bs4',
              'venv.lib.python3.6.site-packages.bs4.tests', 'venv.lib.python3.6.site-packages.bs4.builder',
              'venv.lib.python3.6.site-packages.pip', 'venv.lib.python3.6.site-packages.pip._vendor',
              'venv.lib.python3.6.site-packages.pip._vendor.idna',
              'venv.lib.python3.6.site-packages.pip._vendor.pep517',
              'venv.lib.python3.6.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.6.site-packages.pip._vendor.certifi',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip._internal', 'venv.lib.python3.6.site-packages.pip._internal.cli',
              'venv.lib.python3.6.site-packages.pip._internal.req',
              'venv.lib.python3.6.site-packages.pip._internal.vcs',
              'venv.lib.python3.6.site-packages.pip._internal.utils',
              'venv.lib.python3.6.site-packages.pip._internal.models',
              'venv.lib.python3.6.site-packages.pip._internal.commands',
              'venv.lib.python3.6.site-packages.pip._internal.operations', 'venv.lib.python3.6.site-packages.attr',
              'venv.lib.python3.6.site-packages.bson', 'venv.lib.python3.6.site-packages.idna',
              'venv.lib.python3.6.site-packages.lxml', 'venv.lib.python3.6.site-packages.lxml.html',
              'venv.lib.python3.6.site-packages.lxml.includes', 'venv.lib.python3.6.site-packages.lxml.isoschematron',
              'venv.lib.python3.6.site-packages.nltk', 'venv.lib.python3.6.site-packages.nltk.app',
              'venv.lib.python3.6.site-packages.nltk.ccg', 'venv.lib.python3.6.site-packages.nltk.sem',
              'venv.lib.python3.6.site-packages.nltk.tag', 'venv.lib.python3.6.site-packages.nltk.tbl',
              'venv.lib.python3.6.site-packages.nltk.chat', 'venv.lib.python3.6.site-packages.nltk.draw',
              'venv.lib.python3.6.site-packages.nltk.misc', 'venv.lib.python3.6.site-packages.nltk.stem',
              'venv.lib.python3.6.site-packages.nltk.test', 'venv.lib.python3.6.site-packages.nltk.test.unit',
              'venv.lib.python3.6.site-packages.nltk.test.unit.translate',
              'venv.lib.python3.6.site-packages.nltk.chunk', 'venv.lib.python3.6.site-packages.nltk.parse',
              'venv.lib.python3.6.site-packages.nltk.corpus', 'venv.lib.python3.6.site-packages.nltk.corpus.reader',
              'venv.lib.python3.6.site-packages.nltk.cluster', 'venv.lib.python3.6.site-packages.nltk.metrics',
              'venv.lib.python3.6.site-packages.nltk.twitter', 'venv.lib.python3.6.site-packages.nltk.classify',
              'venv.lib.python3.6.site-packages.nltk.tokenize', 'venv.lib.python3.6.site-packages.nltk.inference',
              'venv.lib.python3.6.site-packages.nltk.sentiment', 'venv.lib.python3.6.site-packages.nltk.translate',
              'venv.lib.python3.6.site-packages.pytz', 'venv.lib.python3.6.site-packages.yaml',
              'venv.lib.python3.6.site-packages.babel', 'venv.lib.python3.6.site-packages.babel.messages',
              'venv.lib.python3.6.site-packages.babel.localtime', 'venv.lib.python3.6.site-packages.numpy',
              'venv.lib.python3.6.site-packages.numpy.ma', 'venv.lib.python3.6.site-packages.numpy.ma.tests',
              'venv.lib.python3.6.site-packages.numpy.doc', 'venv.lib.python3.6.site-packages.numpy.fft',
              'venv.lib.python3.6.site-packages.numpy.fft.tests', 'venv.lib.python3.6.site-packages.numpy.lib',
              'venv.lib.python3.6.site-packages.numpy.lib.tests', 'venv.lib.python3.6.site-packages.numpy.core',
              'venv.lib.python3.6.site-packages.numpy.core.tests', 'venv.lib.python3.6.site-packages.numpy.f2py',
              'venv.lib.python3.6.site-packages.numpy.f2py.tests', 'venv.lib.python3.6.site-packages.numpy.tests',
              'venv.lib.python3.6.site-packages.numpy.compat', 'venv.lib.python3.6.site-packages.numpy.compat.tests',
              'venv.lib.python3.6.site-packages.numpy.linalg', 'venv.lib.python3.6.site-packages.numpy.linalg.tests',
              'venv.lib.python3.6.site-packages.numpy.random', 'venv.lib.python3.6.site-packages.numpy.random.tests',
              'venv.lib.python3.6.site-packages.numpy.testing', 'venv.lib.python3.6.site-packages.numpy.testing.tests',
              'venv.lib.python3.6.site-packages.numpy.testing._private',
              'venv.lib.python3.6.site-packages.numpy.distutils',
              'venv.lib.python3.6.site-packages.numpy.distutils.tests',
              'venv.lib.python3.6.site-packages.numpy.distutils.command',
              'venv.lib.python3.6.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.6.site-packages.numpy.matrixlib',
              'venv.lib.python3.6.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.6.site-packages.numpy.polynomial',
              'venv.lib.python3.6.site-packages.numpy.polynomial.tests', 'venv.lib.python3.6.site-packages.scipy',
              'venv.lib.python3.6.site-packages.scipy.io', 'venv.lib.python3.6.site-packages.scipy.io.arff',
              'venv.lib.python3.6.site-packages.scipy.io.arff.tests', 'venv.lib.python3.6.site-packages.scipy.io.tests',
              'venv.lib.python3.6.site-packages.scipy.io.matlab',
              'venv.lib.python3.6.site-packages.scipy.io.matlab.tests',
              'venv.lib.python3.6.site-packages.scipy.io.harwell_boeing',
              'venv.lib.python3.6.site-packages.scipy.io.harwell_boeing.tests',
              'venv.lib.python3.6.site-packages.scipy.odr', 'venv.lib.python3.6.site-packages.scipy.odr.tests',
              'venv.lib.python3.6.site-packages.scipy._lib', 'venv.lib.python3.6.site-packages.scipy._lib.tests',
              'venv.lib.python3.6.site-packages.scipy.misc', 'venv.lib.python3.6.site-packages.scipy.misc.tests',
              'venv.lib.python3.6.site-packages.scipy.stats', 'venv.lib.python3.6.site-packages.scipy.stats.tests',
              'venv.lib.python3.6.site-packages.scipy.linalg', 'venv.lib.python3.6.site-packages.scipy.linalg.tests',
              'venv.lib.python3.6.site-packages.scipy.signal', 'venv.lib.python3.6.site-packages.scipy.signal.tests',
              'venv.lib.python3.6.site-packages.scipy.signal.windows', 'venv.lib.python3.6.site-packages.scipy.sparse',
              'venv.lib.python3.6.site-packages.scipy.sparse.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.isolve',
              'venv.lib.python3.6.site-packages.scipy.sparse.linalg.isolve.tests',
              'venv.lib.python3.6.site-packages.scipy.sparse.csgraph',
              'venv.lib.python3.6.site-packages.scipy.sparse.csgraph.tests',
              'venv.lib.python3.6.site-packages.scipy.cluster', 'venv.lib.python3.6.site-packages.scipy.cluster.tests',
              'venv.lib.python3.6.site-packages.scipy.fftpack', 'venv.lib.python3.6.site-packages.scipy.fftpack.tests',
              'venv.lib.python3.6.site-packages.scipy.ndimage', 'venv.lib.python3.6.site-packages.scipy.ndimage.tests',
              'venv.lib.python3.6.site-packages.scipy.spatial', 'venv.lib.python3.6.site-packages.scipy.spatial.tests',
              'venv.lib.python3.6.site-packages.scipy.special', 'venv.lib.python3.6.site-packages.scipy.special.tests',
              'venv.lib.python3.6.site-packages.scipy.special._precompute',
              'venv.lib.python3.6.site-packages.scipy.optimize', 'venv.lib.python3.6.site-packages.scipy.optimize._lsq',
              'venv.lib.python3.6.site-packages.scipy.optimize.tests',
              'venv.lib.python3.6.site-packages.scipy.optimize._trlib',
              'venv.lib.python3.6.site-packages.scipy.optimize._trustregion_constr',
              'venv.lib.python3.6.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.lib.python3.6.site-packages.scipy.constants',
              'venv.lib.python3.6.site-packages.scipy.constants.tests',
              'venv.lib.python3.6.site-packages.scipy.integrate',
              'venv.lib.python3.6.site-packages.scipy.integrate._ivp',
              'venv.lib.python3.6.site-packages.scipy.integrate.tests',
              'venv.lib.python3.6.site-packages.scipy.interpolate',
              'venv.lib.python3.6.site-packages.scipy.interpolate.tests',
              'venv.lib.python3.6.site-packages.scipy._build_utils', 'venv.lib.python3.6.site-packages.gridfs',
              'venv.lib.python3.6.site-packages.jinja2', 'venv.lib.python3.6.site-packages.pandas',
              'venv.lib.python3.6.site-packages.pandas.io', 'venv.lib.python3.6.site-packages.pandas.io.sas',
              'venv.lib.python3.6.site-packages.pandas.io.json', 'venv.lib.python3.6.site-packages.pandas.io.formats',
              'venv.lib.python3.6.site-packages.pandas.io.msgpack',
              'venv.lib.python3.6.site-packages.pandas.io.clipboard', 'venv.lib.python3.6.site-packages.pandas.api',
              'venv.lib.python3.6.site-packages.pandas.api.types',
              'venv.lib.python3.6.site-packages.pandas.api.extensions', 'venv.lib.python3.6.site-packages.pandas.core',
              'venv.lib.python3.6.site-packages.pandas.core.util', 'venv.lib.python3.6.site-packages.pandas.core.tools',
              'venv.lib.python3.6.site-packages.pandas.core.arrays',
              'venv.lib.python3.6.site-packages.pandas.core.dtypes',
              'venv.lib.python3.6.site-packages.pandas.core.sparse',
              'venv.lib.python3.6.site-packages.pandas.core.groupby',
              'venv.lib.python3.6.site-packages.pandas.core.indexes',
              'venv.lib.python3.6.site-packages.pandas.core.reshape',
              'venv.lib.python3.6.site-packages.pandas.core.computation',
              'venv.lib.python3.6.site-packages.pandas.util', 'venv.lib.python3.6.site-packages.pandas._libs',
              'venv.lib.python3.6.site-packages.pandas._libs.tslibs', 'venv.lib.python3.6.site-packages.pandas.tests',
              'venv.lib.python3.6.site-packages.pandas.tests.io',
              'venv.lib.python3.6.site-packages.pandas.tests.io.sas',
              'venv.lib.python3.6.site-packages.pandas.tests.io.json',
              'venv.lib.python3.6.site-packages.pandas.tests.io.parser',
              'venv.lib.python3.6.site-packages.pandas.tests.io.formats',
              'venv.lib.python3.6.site-packages.pandas.tests.io.msgpack',
              'venv.lib.python3.6.site-packages.pandas.tests.api', 'venv.lib.python3.6.site-packages.pandas.tests.util',
              'venv.lib.python3.6.site-packages.pandas.tests.frame',
              'venv.lib.python3.6.site-packages.pandas.tests.tools',
              'venv.lib.python3.6.site-packages.pandas.tests.dtypes',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.period',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.interval',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.timedelta',
              'venv.lib.python3.6.site-packages.pandas.tests.scalar.timestamp',
              'venv.lib.python3.6.site-packages.pandas.tests.series',
              'venv.lib.python3.6.site-packages.pandas.tests.series.indexing',
              'venv.lib.python3.6.site-packages.pandas.tests.sparse',
              'venv.lib.python3.6.site-packages.pandas.tests.sparse.frame',
              'venv.lib.python3.6.site-packages.pandas.tests.sparse.series',
              'venv.lib.python3.6.site-packages.pandas.tests.tslibs',
              'venv.lib.python3.6.site-packages.pandas.tests.generic',
              'venv.lib.python3.6.site-packages.pandas.tests.groupby',
              'venv.lib.python3.6.site-packages.pandas.tests.groupby.aggregate',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.period',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.interval',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib.python3.6.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib.python3.6.site-packages.pandas.tests.reshape',
              'venv.lib.python3.6.site-packages.pandas.tests.reshape.merge',
              'venv.lib.python3.6.site-packages.pandas.tests.tseries',
              'venv.lib.python3.6.site-packages.pandas.tests.tseries.offsets',
              'venv.lib.python3.6.site-packages.pandas.tests.indexing',
              'venv.lib.python3.6.site-packages.pandas.tests.indexing.interval',
              'venv.lib.python3.6.site-packages.pandas.tests.plotting',
              'venv.lib.python3.6.site-packages.pandas.tests.extension',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.base',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.json',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.decimal',
              'venv.lib.python3.6.site-packages.pandas.tests.extension.category',
              'venv.lib.python3.6.site-packages.pandas.tests.internals',
              'venv.lib.python3.6.site-packages.pandas.tests.categorical',
              'venv.lib.python3.6.site-packages.pandas.tests.computation',
              'venv.lib.python3.6.site-packages.pandas.tools', 'venv.lib.python3.6.site-packages.pandas.types',
              'venv.lib.python3.6.site-packages.pandas.compat', 'venv.lib.python3.6.site-packages.pandas.compat.numpy',
              'venv.lib.python3.6.site-packages.pandas.errors', 'venv.lib.python3.6.site-packages.pandas.formats',
              'venv.lib.python3.6.site-packages.pandas.tseries', 'venv.lib.python3.6.site-packages.pandas.plotting',
              'venv.lib.python3.6.site-packages.pandas.computation', 'venv.lib.python3.6.site-packages.pluggy',
              'venv.lib.python3.6.site-packages.sphinx', 'venv.lib.python3.6.site-packages.sphinx.cmd',
              'venv.lib.python3.6.site-packages.sphinx.ext', 'venv.lib.python3.6.site-packages.sphinx.ext.autodoc',
              'venv.lib.python3.6.site-packages.sphinx.ext.napoleon',
              'venv.lib.python3.6.site-packages.sphinx.ext.autosummary', 'venv.lib.python3.6.site-packages.sphinx.util',
              'venv.lib.python3.6.site-packages.sphinx.util.stemmer', 'venv.lib.python3.6.site-packages.sphinx.locale',
              'venv.lib.python3.6.site-packages.sphinx.pycode', 'venv.lib.python3.6.site-packages.sphinx.search',
              'venv.lib.python3.6.site-packages.sphinx.domains', 'venv.lib.python3.6.site-packages.sphinx.testing',
              'venv.lib.python3.6.site-packages.sphinx.writers', 'venv.lib.python3.6.site-packages.sphinx.builders',
              'venv.lib.python3.6.site-packages.sphinx.builders.latex',
              'venv.lib.python3.6.site-packages.sphinx.directives',
              'venv.lib.python3.6.site-packages.sphinx.transforms',
              'venv.lib.python3.6.site-packages.sphinx.transforms.post_transforms',
              'venv.lib.python3.6.site-packages.sphinx.websupport',
              'venv.lib.python3.6.site-packages.sphinx.websupport.search',
              'venv.lib.python3.6.site-packages.sphinx.websupport.storage',
              'venv.lib.python3.6.site-packages.sphinx.environment',
              'venv.lib.python3.6.site-packages.sphinx.environment.adapters',
              'venv.lib.python3.6.site-packages.sphinx.environment.collectors',
              'venv.lib.python3.6.site-packages._pytest', 'venv.lib.python3.6.site-packages._pytest.mark',
              'venv.lib.python3.6.site-packages._pytest._code', 'venv.lib.python3.6.site-packages._pytest.config',
              'venv.lib.python3.6.site-packages._pytest.assertion', 'venv.lib.python3.6.site-packages.certifi',
              'venv.lib.python3.6.site-packages.chardet', 'venv.lib.python3.6.site-packages.chardet.cli',
              'venv.lib.python3.6.site-packages.pymongo', 'venv.lib.python3.6.site-packages.sklearn',
              'venv.lib.python3.6.site-packages.sklearn.svm', 'venv.lib.python3.6.site-packages.sklearn.svm.tests',
              'venv.lib.python3.6.site-packages.sklearn.tree', 'venv.lib.python3.6.site-packages.sklearn.tree.tests',
              'venv.lib.python3.6.site-packages.sklearn.tests', 'venv.lib.python3.6.site-packages.sklearn.utils',
              'venv.lib.python3.6.site-packages.sklearn.utils.tests',
              'venv.lib.python3.6.site-packages.sklearn.utils.sparsetools',
              'venv.lib.python3.6.site-packages.sklearn.utils.sparsetools.tests',
              'venv.lib.python3.6.site-packages.sklearn.cluster',
              'venv.lib.python3.6.site-packages.sklearn.cluster.tests',
              'venv.lib.python3.6.site-packages.sklearn.compose',
              'venv.lib.python3.6.site-packages.sklearn.compose.tests',
              'venv.lib.python3.6.site-packages.sklearn.metrics',
              'venv.lib.python3.6.site-packages.sklearn.metrics.tests',
              'venv.lib.python3.6.site-packages.sklearn.metrics.cluster',
              'venv.lib.python3.6.site-packages.sklearn.metrics.cluster.tests',
              'venv.lib.python3.6.site-packages.sklearn.mixture',
              'venv.lib.python3.6.site-packages.sklearn.mixture.tests',
              'venv.lib.python3.6.site-packages.sklearn.datasets',
              'venv.lib.python3.6.site-packages.sklearn.datasets.tests',
              'venv.lib.python3.6.site-packages.sklearn.ensemble',
              'venv.lib.python3.6.site-packages.sklearn.ensemble.tests',
              'venv.lib.python3.6.site-packages.sklearn.manifold',
              'venv.lib.python3.6.site-packages.sklearn.manifold.tests',
              'venv.lib.python3.6.site-packages.sklearn.externals',
              'venv.lib.python3.6.site-packages.sklearn.externals.joblib',
              'venv.lib.python3.6.site-packages.sklearn.externals.joblib.externals',
              'venv.lib.python3.6.site-packages.sklearn.externals.joblib.externals.loky',
              'venv.lib.python3.6.site-packages.sklearn.externals.joblib.externals.loky.backend',
              'venv.lib.python3.6.site-packages.sklearn.externals.joblib.externals.cloudpickle',
              'venv.lib.python3.6.site-packages.sklearn.neighbors',
              'venv.lib.python3.6.site-packages.sklearn.neighbors.tests',
              'venv.lib.python3.6.site-packages.sklearn.covariance',
              'venv.lib.python3.6.site-packages.sklearn.covariance.tests',
              'venv.lib.python3.6.site-packages.sklearn._build_utils',
              'venv.lib.python3.6.site-packages.sklearn.linear_model',
              'venv.lib.python3.6.site-packages.sklearn.linear_model.tests',
              'venv.lib.python3.6.site-packages.sklearn.__check_build',
              'venv.lib.python3.6.site-packages.sklearn.decomposition',
              'venv.lib.python3.6.site-packages.sklearn.decomposition.tests',
              'venv.lib.python3.6.site-packages.sklearn.preprocessing',
              'venv.lib.python3.6.site-packages.sklearn.preprocessing.tests',
              'venv.lib.python3.6.site-packages.sklearn.neural_network',
              'venv.lib.python3.6.site-packages.sklearn.neural_network.tests',
              'venv.lib.python3.6.site-packages.sklearn.model_selection',
              'venv.lib.python3.6.site-packages.sklearn.model_selection.tests',
              'venv.lib.python3.6.site-packages.sklearn.semi_supervised',
              'venv.lib.python3.6.site-packages.sklearn.semi_supervised.tests',
              'venv.lib.python3.6.site-packages.sklearn.gaussian_process',
              'venv.lib.python3.6.site-packages.sklearn.gaussian_process.tests',
              'venv.lib.python3.6.site-packages.sklearn.feature_selection',
              'venv.lib.python3.6.site-packages.sklearn.feature_selection.tests',
              'venv.lib.python3.6.site-packages.sklearn.feature_extraction',
              'venv.lib.python3.6.site-packages.sklearn.feature_extraction.tests',
              'venv.lib.python3.6.site-packages.sklearn.cross_decomposition',
              'venv.lib.python3.6.site-packages.sklearn.cross_decomposition.tests',
              'venv.lib.python3.6.site-packages.urllib3', 'venv.lib.python3.6.site-packages.urllib3.util',
              'venv.lib.python3.6.site-packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.dateutil', 'venv.lib.python3.6.site-packages.dateutil.tz',
              'venv.lib.python3.6.site-packages.dateutil.parser', 'venv.lib.python3.6.site-packages.dateutil.zoneinfo',
              'venv.lib.python3.6.site-packages.docutils', 'venv.lib.python3.6.site-packages.docutils.utils',
              'venv.lib.python3.6.site-packages.docutils.utils.math',
              'venv.lib.python3.6.site-packages.docutils.parsers',
              'venv.lib.python3.6.site-packages.docutils.parsers.rst',
              'venv.lib.python3.6.site-packages.docutils.parsers.rst.languages',
              'venv.lib.python3.6.site-packages.docutils.parsers.rst.directives',
              'venv.lib.python3.6.site-packages.docutils.readers', 'venv.lib.python3.6.site-packages.docutils.writers',
              'venv.lib.python3.6.site-packages.docutils.writers.xetex',
              'venv.lib.python3.6.site-packages.docutils.writers.latex2e',
              'venv.lib.python3.6.site-packages.docutils.writers.odf_odt',
              'venv.lib.python3.6.site-packages.docutils.writers.s5_html',
              'venv.lib.python3.6.site-packages.docutils.writers.pep_html',
              'venv.lib.python3.6.site-packages.docutils.writers.html4css1',
              'venv.lib.python3.6.site-packages.docutils.writers.html5_polyglot',
              'venv.lib.python3.6.site-packages.docutils.languages',
              'venv.lib.python3.6.site-packages.docutils.transforms', 'venv.lib.python3.6.site-packages.pygments',
              'venv.lib.python3.6.site-packages.pygments.lexers', 'venv.lib.python3.6.site-packages.pygments.styles',
              'venv.lib.python3.6.site-packages.pygments.filters',
              'venv.lib.python3.6.site-packages.pygments.formatters', 'venv.lib.python3.6.site-packages.requests',
              'venv.lib.python3.6.site-packages.alabaster', 'venv.lib.python3.6.site-packages.packaging',
              'venv.lib.python3.6.site-packages.markupsafe', 'venv.lib.python3.6.site-packages.atomicwrites',
              'venv.lib.python3.6.site-packages.sphinxcontrib.websupport',
              'venv.lib.python3.6.site-packages.sphinxcontrib.websupport.search',
              'venv.lib.python3.6.site-packages.sphinxcontrib.websupport.storage',
              'venv.lib.python3.6.site-packages.more_itertools',
              'venv.lib.python3.6.site-packages.more_itertools.tests',
              'venv.lib.python3.6.site-packages.snowballstemmer', 'venv.lib64.python3.6.site-packages.py',
              'venv.lib64.python3.6.site-packages.py._io', 'venv.lib64.python3.6.site-packages.py._log',
              'venv.lib64.python3.6.site-packages.py._code', 'venv.lib64.python3.6.site-packages.py._path',
              'venv.lib64.python3.6.site-packages.py._process',
              'venv.lib64.python3.6.site-packages.py._vendored_packages', 'venv.lib64.python3.6.site-packages.bs4',
              'venv.lib64.python3.6.site-packages.bs4.tests', 'venv.lib64.python3.6.site-packages.bs4.builder',
              'venv.lib64.python3.6.site-packages.pip', 'venv.lib64.python3.6.site-packages.pip._vendor',
              'venv.lib64.python3.6.site-packages.pip._vendor.idna',
              'venv.lib64.python3.6.site-packages.pip._vendor.pep517',
              'venv.lib64.python3.6.site-packages.pip._vendor.pytoml',
              'venv.lib64.python3.6.site-packages.pip._vendor.certifi',
              'venv.lib64.python3.6.site-packages.pip._vendor.chardet',
              'venv.lib64.python3.6.site-packages.pip._vendor.chardet.cli',
              'venv.lib64.python3.6.site-packages.pip._vendor.distlib',
              'venv.lib64.python3.6.site-packages.pip._vendor.distlib._backport',
              'venv.lib64.python3.6.site-packages.pip._vendor.msgpack',
              'venv.lib64.python3.6.site-packages.pip._vendor.urllib3',
              'venv.lib64.python3.6.site-packages.pip._vendor.urllib3.util',
              'venv.lib64.python3.6.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib64.python3.6.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib64.python3.6.site-packages.pip._vendor.urllib3.packages',
              'venv.lib64.python3.6.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib64.python3.6.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib64.python3.6.site-packages.pip._vendor.colorama',
              'venv.lib64.python3.6.site-packages.pip._vendor.html5lib',
              'venv.lib64.python3.6.site-packages.pip._vendor.html5lib._trie',
              'venv.lib64.python3.6.site-packages.pip._vendor.html5lib.filters',
              'venv.lib64.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib64.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib64.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib64.python3.6.site-packages.pip._vendor.lockfile',
              'venv.lib64.python3.6.site-packages.pip._vendor.progress',
              'venv.lib64.python3.6.site-packages.pip._vendor.requests',
              'venv.lib64.python3.6.site-packages.pip._vendor.packaging',
              'venv.lib64.python3.6.site-packages.pip._vendor.cachecontrol',
              'venv.lib64.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib64.python3.6.site-packages.pip._vendor.webencodings',
              'venv.lib64.python3.6.site-packages.pip._vendor.pkg_resources',
              'venv.lib64.python3.6.site-packages.pip._internal',
              'venv.lib64.python3.6.site-packages.pip._internal.cli',
              'venv.lib64.python3.6.site-packages.pip._internal.req',
              'venv.lib64.python3.6.site-packages.pip._internal.vcs',
              'venv.lib64.python3.6.site-packages.pip._internal.utils',
              'venv.lib64.python3.6.site-packages.pip._internal.models',
              'venv.lib64.python3.6.site-packages.pip._internal.commands',
              'venv.lib64.python3.6.site-packages.pip._internal.operations', 'venv.lib64.python3.6.site-packages.attr',
              'venv.lib64.python3.6.site-packages.bson', 'venv.lib64.python3.6.site-packages.idna',
              'venv.lib64.python3.6.site-packages.lxml', 'venv.lib64.python3.6.site-packages.lxml.html',
              'venv.lib64.python3.6.site-packages.lxml.includes',
              'venv.lib64.python3.6.site-packages.lxml.isoschematron', 'venv.lib64.python3.6.site-packages.nltk',
              'venv.lib64.python3.6.site-packages.nltk.app', 'venv.lib64.python3.6.site-packages.nltk.ccg',
              'venv.lib64.python3.6.site-packages.nltk.sem', 'venv.lib64.python3.6.site-packages.nltk.tag',
              'venv.lib64.python3.6.site-packages.nltk.tbl', 'venv.lib64.python3.6.site-packages.nltk.chat',
              'venv.lib64.python3.6.site-packages.nltk.draw', 'venv.lib64.python3.6.site-packages.nltk.misc',
              'venv.lib64.python3.6.site-packages.nltk.stem', 'venv.lib64.python3.6.site-packages.nltk.test',
              'venv.lib64.python3.6.site-packages.nltk.test.unit',
              'venv.lib64.python3.6.site-packages.nltk.test.unit.translate',
              'venv.lib64.python3.6.site-packages.nltk.chunk', 'venv.lib64.python3.6.site-packages.nltk.parse',
              'venv.lib64.python3.6.site-packages.nltk.corpus', 'venv.lib64.python3.6.site-packages.nltk.corpus.reader',
              'venv.lib64.python3.6.site-packages.nltk.cluster', 'venv.lib64.python3.6.site-packages.nltk.metrics',
              'venv.lib64.python3.6.site-packages.nltk.twitter', 'venv.lib64.python3.6.site-packages.nltk.classify',
              'venv.lib64.python3.6.site-packages.nltk.tokenize', 'venv.lib64.python3.6.site-packages.nltk.inference',
              'venv.lib64.python3.6.site-packages.nltk.sentiment', 'venv.lib64.python3.6.site-packages.nltk.translate',
              'venv.lib64.python3.6.site-packages.pytz', 'venv.lib64.python3.6.site-packages.yaml',
              'venv.lib64.python3.6.site-packages.babel', 'venv.lib64.python3.6.site-packages.babel.messages',
              'venv.lib64.python3.6.site-packages.babel.localtime', 'venv.lib64.python3.6.site-packages.numpy',
              'venv.lib64.python3.6.site-packages.numpy.ma', 'venv.lib64.python3.6.site-packages.numpy.ma.tests',
              'venv.lib64.python3.6.site-packages.numpy.doc', 'venv.lib64.python3.6.site-packages.numpy.fft',
              'venv.lib64.python3.6.site-packages.numpy.fft.tests', 'venv.lib64.python3.6.site-packages.numpy.lib',
              'venv.lib64.python3.6.site-packages.numpy.lib.tests', 'venv.lib64.python3.6.site-packages.numpy.core',
              'venv.lib64.python3.6.site-packages.numpy.core.tests', 'venv.lib64.python3.6.site-packages.numpy.f2py',
              'venv.lib64.python3.6.site-packages.numpy.f2py.tests', 'venv.lib64.python3.6.site-packages.numpy.tests',
              'venv.lib64.python3.6.site-packages.numpy.compat',
              'venv.lib64.python3.6.site-packages.numpy.compat.tests',
              'venv.lib64.python3.6.site-packages.numpy.linalg',
              'venv.lib64.python3.6.site-packages.numpy.linalg.tests',
              'venv.lib64.python3.6.site-packages.numpy.random',
              'venv.lib64.python3.6.site-packages.numpy.random.tests',
              'venv.lib64.python3.6.site-packages.numpy.testing',
              'venv.lib64.python3.6.site-packages.numpy.testing.tests',
              'venv.lib64.python3.6.site-packages.numpy.testing._private',
              'venv.lib64.python3.6.site-packages.numpy.distutils',
              'venv.lib64.python3.6.site-packages.numpy.distutils.tests',
              'venv.lib64.python3.6.site-packages.numpy.distutils.command',
              'venv.lib64.python3.6.site-packages.numpy.distutils.fcompiler',
              'venv.lib64.python3.6.site-packages.numpy.matrixlib',
              'venv.lib64.python3.6.site-packages.numpy.matrixlib.tests',
              'venv.lib64.python3.6.site-packages.numpy.polynomial',
              'venv.lib64.python3.6.site-packages.numpy.polynomial.tests', 'venv.lib64.python3.6.site-packages.scipy',
              'venv.lib64.python3.6.site-packages.scipy.io', 'venv.lib64.python3.6.site-packages.scipy.io.arff',
              'venv.lib64.python3.6.site-packages.scipy.io.arff.tests',
              'venv.lib64.python3.6.site-packages.scipy.io.tests', 'venv.lib64.python3.6.site-packages.scipy.io.matlab',
              'venv.lib64.python3.6.site-packages.scipy.io.matlab.tests',
              'venv.lib64.python3.6.site-packages.scipy.io.harwell_boeing',
              'venv.lib64.python3.6.site-packages.scipy.io.harwell_boeing.tests',
              'venv.lib64.python3.6.site-packages.scipy.odr', 'venv.lib64.python3.6.site-packages.scipy.odr.tests',
              'venv.lib64.python3.6.site-packages.scipy._lib', 'venv.lib64.python3.6.site-packages.scipy._lib.tests',
              'venv.lib64.python3.6.site-packages.scipy.misc', 'venv.lib64.python3.6.site-packages.scipy.misc.tests',
              'venv.lib64.python3.6.site-packages.scipy.stats', 'venv.lib64.python3.6.site-packages.scipy.stats.tests',
              'venv.lib64.python3.6.site-packages.scipy.linalg',
              'venv.lib64.python3.6.site-packages.scipy.linalg.tests',
              'venv.lib64.python3.6.site-packages.scipy.signal',
              'venv.lib64.python3.6.site-packages.scipy.signal.tests',
              'venv.lib64.python3.6.site-packages.scipy.signal.windows',
              'venv.lib64.python3.6.site-packages.scipy.sparse',
              'venv.lib64.python3.6.site-packages.scipy.sparse.tests',
              'venv.lib64.python3.6.site-packages.scipy.sparse.linalg',
              'venv.lib64.python3.6.site-packages.scipy.sparse.linalg.eigen',
              'venv.lib64.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.lib64.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.lib64.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.lib64.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.lib64.python3.6.site-packages.scipy.sparse.linalg.tests',
              'venv.lib64.python3.6.site-packages.scipy.sparse.linalg.dsolve',
              'venv.lib64.python3.6.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.lib64.python3.6.site-packages.scipy.sparse.linalg.isolve',
              'venv.lib64.python3.6.site-packages.scipy.sparse.linalg.isolve.tests',
              'venv.lib64.python3.6.site-packages.scipy.sparse.csgraph',
              'venv.lib64.python3.6.site-packages.scipy.sparse.csgraph.tests',
              'venv.lib64.python3.6.site-packages.scipy.cluster',
              'venv.lib64.python3.6.site-packages.scipy.cluster.tests',
              'venv.lib64.python3.6.site-packages.scipy.fftpack',
              'venv.lib64.python3.6.site-packages.scipy.fftpack.tests',
              'venv.lib64.python3.6.site-packages.scipy.ndimage',
              'venv.lib64.python3.6.site-packages.scipy.ndimage.tests',
              'venv.lib64.python3.6.site-packages.scipy.spatial',
              'venv.lib64.python3.6.site-packages.scipy.spatial.tests',
              'venv.lib64.python3.6.site-packages.scipy.special',
              'venv.lib64.python3.6.site-packages.scipy.special.tests',
              'venv.lib64.python3.6.site-packages.scipy.special._precompute',
              'venv.lib64.python3.6.site-packages.scipy.optimize',
              'venv.lib64.python3.6.site-packages.scipy.optimize._lsq',
              'venv.lib64.python3.6.site-packages.scipy.optimize.tests',
              'venv.lib64.python3.6.site-packages.scipy.optimize._trlib',
              'venv.lib64.python3.6.site-packages.scipy.optimize._trustregion_constr',
              'venv.lib64.python3.6.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.lib64.python3.6.site-packages.scipy.constants',
              'venv.lib64.python3.6.site-packages.scipy.constants.tests',
              'venv.lib64.python3.6.site-packages.scipy.integrate',
              'venv.lib64.python3.6.site-packages.scipy.integrate._ivp',
              'venv.lib64.python3.6.site-packages.scipy.integrate.tests',
              'venv.lib64.python3.6.site-packages.scipy.interpolate',
              'venv.lib64.python3.6.site-packages.scipy.interpolate.tests',
              'venv.lib64.python3.6.site-packages.scipy._build_utils', 'venv.lib64.python3.6.site-packages.gridfs',
              'venv.lib64.python3.6.site-packages.jinja2', 'venv.lib64.python3.6.site-packages.pandas',
              'venv.lib64.python3.6.site-packages.pandas.io', 'venv.lib64.python3.6.site-packages.pandas.io.sas',
              'venv.lib64.python3.6.site-packages.pandas.io.json',
              'venv.lib64.python3.6.site-packages.pandas.io.formats',
              'venv.lib64.python3.6.site-packages.pandas.io.msgpack',
              'venv.lib64.python3.6.site-packages.pandas.io.clipboard', 'venv.lib64.python3.6.site-packages.pandas.api',
              'venv.lib64.python3.6.site-packages.pandas.api.types',
              'venv.lib64.python3.6.site-packages.pandas.api.extensions',
              'venv.lib64.python3.6.site-packages.pandas.core', 'venv.lib64.python3.6.site-packages.pandas.core.util',
              'venv.lib64.python3.6.site-packages.pandas.core.tools',
              'venv.lib64.python3.6.site-packages.pandas.core.arrays',
              'venv.lib64.python3.6.site-packages.pandas.core.dtypes',
              'venv.lib64.python3.6.site-packages.pandas.core.sparse',
              'venv.lib64.python3.6.site-packages.pandas.core.groupby',
              'venv.lib64.python3.6.site-packages.pandas.core.indexes',
              'venv.lib64.python3.6.site-packages.pandas.core.reshape',
              'venv.lib64.python3.6.site-packages.pandas.core.computation',
              'venv.lib64.python3.6.site-packages.pandas.util', 'venv.lib64.python3.6.site-packages.pandas._libs',
              'venv.lib64.python3.6.site-packages.pandas._libs.tslibs',
              'venv.lib64.python3.6.site-packages.pandas.tests', 'venv.lib64.python3.6.site-packages.pandas.tests.io',
              'venv.lib64.python3.6.site-packages.pandas.tests.io.sas',
              'venv.lib64.python3.6.site-packages.pandas.tests.io.json',
              'venv.lib64.python3.6.site-packages.pandas.tests.io.parser',
              'venv.lib64.python3.6.site-packages.pandas.tests.io.formats',
              'venv.lib64.python3.6.site-packages.pandas.tests.io.msgpack',
              'venv.lib64.python3.6.site-packages.pandas.tests.api',
              'venv.lib64.python3.6.site-packages.pandas.tests.util',
              'venv.lib64.python3.6.site-packages.pandas.tests.frame',
              'venv.lib64.python3.6.site-packages.pandas.tests.tools',
              'venv.lib64.python3.6.site-packages.pandas.tests.dtypes',
              'venv.lib64.python3.6.site-packages.pandas.tests.scalar',
              'venv.lib64.python3.6.site-packages.pandas.tests.scalar.period',
              'venv.lib64.python3.6.site-packages.pandas.tests.scalar.interval',
              'venv.lib64.python3.6.site-packages.pandas.tests.scalar.timedelta',
              'venv.lib64.python3.6.site-packages.pandas.tests.scalar.timestamp',
              'venv.lib64.python3.6.site-packages.pandas.tests.series',
              'venv.lib64.python3.6.site-packages.pandas.tests.series.indexing',
              'venv.lib64.python3.6.site-packages.pandas.tests.sparse',
              'venv.lib64.python3.6.site-packages.pandas.tests.sparse.frame',
              'venv.lib64.python3.6.site-packages.pandas.tests.sparse.series',
              'venv.lib64.python3.6.site-packages.pandas.tests.tslibs',
              'venv.lib64.python3.6.site-packages.pandas.tests.generic',
              'venv.lib64.python3.6.site-packages.pandas.tests.groupby',
              'venv.lib64.python3.6.site-packages.pandas.tests.groupby.aggregate',
              'venv.lib64.python3.6.site-packages.pandas.tests.indexes',
              'venv.lib64.python3.6.site-packages.pandas.tests.indexes.period',
              'venv.lib64.python3.6.site-packages.pandas.tests.indexes.interval',
              'venv.lib64.python3.6.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib64.python3.6.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib64.python3.6.site-packages.pandas.tests.reshape',
              'venv.lib64.python3.6.site-packages.pandas.tests.reshape.merge',
              'venv.lib64.python3.6.site-packages.pandas.tests.tseries',
              'venv.lib64.python3.6.site-packages.pandas.tests.tseries.offsets',
              'venv.lib64.python3.6.site-packages.pandas.tests.indexing',
              'venv.lib64.python3.6.site-packages.pandas.tests.indexing.interval',
              'venv.lib64.python3.6.site-packages.pandas.tests.plotting',
              'venv.lib64.python3.6.site-packages.pandas.tests.extension',
              'venv.lib64.python3.6.site-packages.pandas.tests.extension.base',
              'venv.lib64.python3.6.site-packages.pandas.tests.extension.json',
              'venv.lib64.python3.6.site-packages.pandas.tests.extension.decimal',
              'venv.lib64.python3.6.site-packages.pandas.tests.extension.category',
              'venv.lib64.python3.6.site-packages.pandas.tests.internals',
              'venv.lib64.python3.6.site-packages.pandas.tests.categorical',
              'venv.lib64.python3.6.site-packages.pandas.tests.computation',
              'venv.lib64.python3.6.site-packages.pandas.tools', 'venv.lib64.python3.6.site-packages.pandas.types',
              'venv.lib64.python3.6.site-packages.pandas.compat',
              'venv.lib64.python3.6.site-packages.pandas.compat.numpy',
              'venv.lib64.python3.6.site-packages.pandas.errors', 'venv.lib64.python3.6.site-packages.pandas.formats',
              'venv.lib64.python3.6.site-packages.pandas.tseries', 'venv.lib64.python3.6.site-packages.pandas.plotting',
              'venv.lib64.python3.6.site-packages.pandas.computation', 'venv.lib64.python3.6.site-packages.pluggy',
              'venv.lib64.python3.6.site-packages.sphinx', 'venv.lib64.python3.6.site-packages.sphinx.cmd',
              'venv.lib64.python3.6.site-packages.sphinx.ext', 'venv.lib64.python3.6.site-packages.sphinx.ext.autodoc',
              'venv.lib64.python3.6.site-packages.sphinx.ext.napoleon',
              'venv.lib64.python3.6.site-packages.sphinx.ext.autosummary',
              'venv.lib64.python3.6.site-packages.sphinx.util',
              'venv.lib64.python3.6.site-packages.sphinx.util.stemmer',
              'venv.lib64.python3.6.site-packages.sphinx.locale', 'venv.lib64.python3.6.site-packages.sphinx.pycode',
              'venv.lib64.python3.6.site-packages.sphinx.search', 'venv.lib64.python3.6.site-packages.sphinx.domains',
              'venv.lib64.python3.6.site-packages.sphinx.testing', 'venv.lib64.python3.6.site-packages.sphinx.writers',
              'venv.lib64.python3.6.site-packages.sphinx.builders',
              'venv.lib64.python3.6.site-packages.sphinx.builders.latex',
              'venv.lib64.python3.6.site-packages.sphinx.directives',
              'venv.lib64.python3.6.site-packages.sphinx.transforms',
              'venv.lib64.python3.6.site-packages.sphinx.transforms.post_transforms',
              'venv.lib64.python3.6.site-packages.sphinx.websupport',
              'venv.lib64.python3.6.site-packages.sphinx.websupport.search',
              'venv.lib64.python3.6.site-packages.sphinx.websupport.storage',
              'venv.lib64.python3.6.site-packages.sphinx.environment',
              'venv.lib64.python3.6.site-packages.sphinx.environment.adapters',
              'venv.lib64.python3.6.site-packages.sphinx.environment.collectors',
              'venv.lib64.python3.6.site-packages._pytest', 'venv.lib64.python3.6.site-packages._pytest.mark',
              'venv.lib64.python3.6.site-packages._pytest._code', 'venv.lib64.python3.6.site-packages._pytest.config',
              'venv.lib64.python3.6.site-packages._pytest.assertion', 'venv.lib64.python3.6.site-packages.certifi',
              'venv.lib64.python3.6.site-packages.chardet', 'venv.lib64.python3.6.site-packages.chardet.cli',
              'venv.lib64.python3.6.site-packages.pymongo', 'venv.lib64.python3.6.site-packages.sklearn',
              'venv.lib64.python3.6.site-packages.sklearn.svm', 'venv.lib64.python3.6.site-packages.sklearn.svm.tests',
              'venv.lib64.python3.6.site-packages.sklearn.tree',
              'venv.lib64.python3.6.site-packages.sklearn.tree.tests',
              'venv.lib64.python3.6.site-packages.sklearn.tests', 'venv.lib64.python3.6.site-packages.sklearn.utils',
              'venv.lib64.python3.6.site-packages.sklearn.utils.tests',
              'venv.lib64.python3.6.site-packages.sklearn.utils.sparsetools',
              'venv.lib64.python3.6.site-packages.sklearn.utils.sparsetools.tests',
              'venv.lib64.python3.6.site-packages.sklearn.cluster',
              'venv.lib64.python3.6.site-packages.sklearn.cluster.tests',
              'venv.lib64.python3.6.site-packages.sklearn.compose',
              'venv.lib64.python3.6.site-packages.sklearn.compose.tests',
              'venv.lib64.python3.6.site-packages.sklearn.metrics',
              'venv.lib64.python3.6.site-packages.sklearn.metrics.tests',
              'venv.lib64.python3.6.site-packages.sklearn.metrics.cluster',
              'venv.lib64.python3.6.site-packages.sklearn.metrics.cluster.tests',
              'venv.lib64.python3.6.site-packages.sklearn.mixture',
              'venv.lib64.python3.6.site-packages.sklearn.mixture.tests',
              'venv.lib64.python3.6.site-packages.sklearn.datasets',
              'venv.lib64.python3.6.site-packages.sklearn.datasets.tests',
              'venv.lib64.python3.6.site-packages.sklearn.ensemble',
              'venv.lib64.python3.6.site-packages.sklearn.ensemble.tests',
              'venv.lib64.python3.6.site-packages.sklearn.manifold',
              'venv.lib64.python3.6.site-packages.sklearn.manifold.tests',
              'venv.lib64.python3.6.site-packages.sklearn.externals',
              'venv.lib64.python3.6.site-packages.sklearn.externals.joblib',
              'venv.lib64.python3.6.site-packages.sklearn.externals.joblib.externals',
              'venv.lib64.python3.6.site-packages.sklearn.externals.joblib.externals.loky',
              'venv.lib64.python3.6.site-packages.sklearn.externals.joblib.externals.loky.backend',
              'venv.lib64.python3.6.site-packages.sklearn.externals.joblib.externals.cloudpickle',
              'venv.lib64.python3.6.site-packages.sklearn.neighbors',
              'venv.lib64.python3.6.site-packages.sklearn.neighbors.tests',
              'venv.lib64.python3.6.site-packages.sklearn.covariance',
              'venv.lib64.python3.6.site-packages.sklearn.covariance.tests',
              'venv.lib64.python3.6.site-packages.sklearn._build_utils',
              'venv.lib64.python3.6.site-packages.sklearn.linear_model',
              'venv.lib64.python3.6.site-packages.sklearn.linear_model.tests',
              'venv.lib64.python3.6.site-packages.sklearn.__check_build',
              'venv.lib64.python3.6.site-packages.sklearn.decomposition',
              'venv.lib64.python3.6.site-packages.sklearn.decomposition.tests',
              'venv.lib64.python3.6.site-packages.sklearn.preprocessing',
              'venv.lib64.python3.6.site-packages.sklearn.preprocessing.tests',
              'venv.lib64.python3.6.site-packages.sklearn.neural_network',
              'venv.lib64.python3.6.site-packages.sklearn.neural_network.tests',
              'venv.lib64.python3.6.site-packages.sklearn.model_selection',
              'venv.lib64.python3.6.site-packages.sklearn.model_selection.tests',
              'venv.lib64.python3.6.site-packages.sklearn.semi_supervised',
              'venv.lib64.python3.6.site-packages.sklearn.semi_supervised.tests',
              'venv.lib64.python3.6.site-packages.sklearn.gaussian_process',
              'venv.lib64.python3.6.site-packages.sklearn.gaussian_process.tests',
              'venv.lib64.python3.6.site-packages.sklearn.feature_selection',
              'venv.lib64.python3.6.site-packages.sklearn.feature_selection.tests',
              'venv.lib64.python3.6.site-packages.sklearn.feature_extraction',
              'venv.lib64.python3.6.site-packages.sklearn.feature_extraction.tests',
              'venv.lib64.python3.6.site-packages.sklearn.cross_decomposition',
              'venv.lib64.python3.6.site-packages.sklearn.cross_decomposition.tests',
              'venv.lib64.python3.6.site-packages.urllib3', 'venv.lib64.python3.6.site-packages.urllib3.util',
              'venv.lib64.python3.6.site-packages.urllib3.contrib',
              'venv.lib64.python3.6.site-packages.urllib3.contrib._securetransport',
              'venv.lib64.python3.6.site-packages.urllib3.packages',
              'venv.lib64.python3.6.site-packages.urllib3.packages.backports',
              'venv.lib64.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib64.python3.6.site-packages.dateutil', 'venv.lib64.python3.6.site-packages.dateutil.tz',
              'venv.lib64.python3.6.site-packages.dateutil.parser',
              'venv.lib64.python3.6.site-packages.dateutil.zoneinfo', 'venv.lib64.python3.6.site-packages.docutils',
              'venv.lib64.python3.6.site-packages.docutils.utils',
              'venv.lib64.python3.6.site-packages.docutils.utils.math',
              'venv.lib64.python3.6.site-packages.docutils.parsers',
              'venv.lib64.python3.6.site-packages.docutils.parsers.rst',
              'venv.lib64.python3.6.site-packages.docutils.parsers.rst.languages',
              'venv.lib64.python3.6.site-packages.docutils.parsers.rst.directives',
              'venv.lib64.python3.6.site-packages.docutils.readers',
              'venv.lib64.python3.6.site-packages.docutils.writers',
              'venv.lib64.python3.6.site-packages.docutils.writers.xetex',
              'venv.lib64.python3.6.site-packages.docutils.writers.latex2e',
              'venv.lib64.python3.6.site-packages.docutils.writers.odf_odt',
              'venv.lib64.python3.6.site-packages.docutils.writers.s5_html',
              'venv.lib64.python3.6.site-packages.docutils.writers.pep_html',
              'venv.lib64.python3.6.site-packages.docutils.writers.html4css1',
              'venv.lib64.python3.6.site-packages.docutils.writers.html5_polyglot',
              'venv.lib64.python3.6.site-packages.docutils.languages',
              'venv.lib64.python3.6.site-packages.docutils.transforms', 'venv.lib64.python3.6.site-packages.pygments',
              'venv.lib64.python3.6.site-packages.pygments.lexers',
              'venv.lib64.python3.6.site-packages.pygments.styles',
              'venv.lib64.python3.6.site-packages.pygments.filters',
              'venv.lib64.python3.6.site-packages.pygments.formatters', 'venv.lib64.python3.6.site-packages.requests',
              'venv.lib64.python3.6.site-packages.alabaster', 'venv.lib64.python3.6.site-packages.packaging',
              'venv.lib64.python3.6.site-packages.markupsafe', 'venv.lib64.python3.6.site-packages.atomicwrites',
              'venv.lib64.python3.6.site-packages.sphinxcontrib.websupport',
              'venv.lib64.python3.6.site-packages.sphinxcontrib.websupport.search',
              'venv.lib64.python3.6.site-packages.sphinxcontrib.websupport.storage',
              'venv.lib64.python3.6.site-packages.more_itertools',
              'venv.lib64.python3.6.site-packages.more_itertools.tests',
              'venv.lib64.python3.6.site-packages.snowballstemmer'],
    url='',
    license='',
    author='Katherine M S Brown',
    author_email='katherinemsbrown@gmail.com',
    description='Code Test for Cisco FSE contract position'
)
